// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using solita_assignment.Models;

#nullable disable

namespace solita_assignment.Migrations
{
    [DbContext(typeof(JourneyContext))]
    [Migration("20230505141232_UpdateStationAndJourneyProperties")]
    partial class UpdateStationAndJourneyProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("solita_assignment.Classes.Journey", b =>
                {
                    b.Property<Guid>("JourneyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("CoveredDistance")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartureStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureStationName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Return")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReturnStationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReturnStationName")
                        .HasColumnType("TEXT");

                    b.HasKey("JourneyId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("solita_assignment.Classes.Station", b =>
                {
                    b.Property<Guid>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressFinnish")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressSwedish")
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityFinnish")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitySwedish")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdInt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LocationX")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LocationY")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameFinnish")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSwedish")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT");

                    b.HasKey("StationId");

                    b.ToTable("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
